if (process.env.NODE_ENV === 'development' || !process.env.NODE_ENV) {
  require('dotenv').config({path: '../.env'})
}
const Character = require('../models/character')
const Player = require('../models/player')
const Session = require('../models/session')
const _ = require('lodash')
const mongoose = require('mongoose')
const Promise = require('bluebird')
mongoose.Promise = Promise
mongoose.connect(process.env.MONGODB_URI)
let players = {}
let sessions = {}

let characters = []
let allData = [
  {
    "Character Name": "Dax",
    "Player Name": "Abrahm",
    "Discord": "AbrahmDivus#6936",
    "Race": "Lizardfolk",
    "Class": "Circle of the Moon Druid",
    "Level": 2,
    "Session Points": 8,
    "Status (See Link)": "",
    "Name of Last Session Played": "An Immovable Feast",
    "Date of Last Session": "6/12/2019",
    "Last City Visited": "Bad Solitz",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Abrahm",
    "Player Name": "Abrahm",
    "Discord": "AbrahmDivus#6936",
    "Race": "Variant Human",
    "Class": "Warlock (Hexblade)",
    "Level": 5,
    "Session Points": 39,
    "Status (See Link)": "",
    "Name of Last Session Played": "Run Like Hell",
    "Date of Last Session": "6/7/2019",
    "Last City Visited": "Stalimisto",
    "System": "D&D5E",
    "Notes": ""
  },
  {
    "Character Name": "Hakon Lysbearer",
    "Player Name": "Sean McNeil",
    "Discord": "acalagus#7518",
    "Race": "Bearfolk",
    "Class": "Barbarian",
    "Level": 7,
    "Session Points": 60,
    "Status (See Link)": "",
    "Name of Last Session Played": "IRL Courts of the Shadow Fey, Session 9",
    "Date of Last Session": "6/19/2019",
    "Last City Visited": "Shadow Realm",
    "System": "D&D 5e",
    "Notes": ""
  },
  {
    "Character Name": "Gaelen Bryn",
    "Player Name": "Nick Landry",
    "Discord": "ActiveNick#6519",
    "Race": "Human (variant)",
    "Class": "Druid, Circle of Stones",
    "Level": 5,
    "Session Points": 38,
    "Status (See Link)": 4,
    "Name of Last Session Played": "An Immovable Feast",
    "Date of Last Session": "6/12/2019",
    "Last City Visited": "Bad Solitz",
    "System": "D&D5E",
    "Notes": ""
  },
  {
    "Character Name": "Khazdakhaal",
    "Player Name": "Nick Landry",
    "Discord": "ActiveNick#6519",
    "Race": "Ramag",
    "Class": "Wizard (Geomancer)",
    "Level": 2,
    "Session Points": 10,
    "Status (See Link)": "",
    "Name of Last Session Played": "Who Runs Castle Ranno, Session 6",
    "Date of Last Session": "7/14/19",
    "Last City Visited": "Ranno (near Triolo)",
    "System": "D&D 5E",
    "Notes": "-5 Status with the Kariv"
  },
  {
    "Character Name": "Soral al-Bashir",
    "Player Name": "Andrew B",
    "Discord": "Andrew B#9215",
    "Race": "Dragonborn (Edjet)",
    "Class": "Fighter",
    "Level": 6,
    "Session Points": 58,
    "Status (See Link)": 15,
    "Name of Last Session Played": "Courts of the Shadow Fey, Session 3 - Online",
    "Date of Last Session": "5/11/2018",
    "Last City Visited": "Zobeck",
    "System": "D&D5E",
    "Notes": ""
  },
  {
    "Character Name": "Toren Lightbane",
    "Player Name": "Andrew B",
    "Discord": "Andrew B#9215",
    "Race": "Darakhul",
    "Class": "Warlock",
    "Level": 2,
    "Session Points": 3,
    "Status (See Link)": "",
    "Name of Last Session Played": "Ooze Who?",
    "Date of Last Session": "6/26/2019",
    "Last City Visited": "Maillon",
    "System": "D&D5E",
    "Notes": ""
  },
  {
    "Character Name": "Marjot",
    "Player Name": "Mike T",
    "Discord": "Atanamar (Mike T)#8540",
    "Race": "Shadow Fey",
    "Class": "Rogue (Swashbuckler)",
    "Level": 4,
    "Session Points": 28,
    "Status (See Link)": "",
    "Name of Last Session Played": "In the Name of Khors",
    "Date of Last Session": "3/22/2019",
    "Last City Visited": "Zobeck",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Idril",
    "Player Name": "Mike T",
    "Discord": "Atanamar (Mike T)#8540",
    "Race": "Variant Human",
    "Class": "Cleric (Time Domain)",
    "Level": 8,
    "Session Points": 76,
    "Status (See Link)": "",
    "Name of Last Session Played": "To Wake War",
    "Date of Last Session": "3/9/2019",
    "Last City Visited": "The Fist of Mavros",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Glyph",
    "Player Name": "Mike T",
    "Discord": "Atanamar (Mike T)#8540",
    "Race": "Winterfolk Halfling",
    "Class": "Paladin (Oath of the Ancients)",
    "Level": 7,
    "Session Points": 64,
    "Status (See Link)": "",
    "Name of Last Session Played": "The Infernal Salt Pits",
    "Date of Last Session": "12/23/2018",
    "Last City Visited": "Saph-Saph",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Ashyn",
    "Player Name": "Mike T",
    "Discord": "Atanamar (Mike T)#8540",
    "Race": "Night Whisper Trollkin",
    "Class": "Druid (Circle of the Land - Mountains)",
    "Level": 3,
    "Session Points": 16,
    "Status (See Link)": "",
    "Name of Last Session Played": "The Forgotten King's Tomb",
    "Date of Last Session": "11/2/2018",
    "Last City Visited": "Mezar",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Dyre",
    "Player Name": "Mike T",
    "Discord": "Atanamar (Mike T)#8540",
    "Race": "Elfmarked",
    "Class": "Druid",
    "Level": 5,
    "Session Points": 39,
    "Status (See Link)": "",
    "Name of Last Session Played": "The Maiden",
    "Date of Last Session": "6/29/2019",
    "Last City Visited": "Savoyne",
    "System": "D&D5E",
    "Notes": ""
  },
  {
    "Character Name": "Pike",
    "Player Name": "Mike T",
    "Discord": "Atanamar (Mike T)#8540",
    "Race": "Variant Human",
    "Class": "Fighter (Prescient Knight)",
    "Level": 3,
    "Session Points": 20,
    "Status (See Link)": "",
    "Name of Last Session Played": "For Science",
    "Date of Last Session": "4/26/19",
    "Last City Visited": "Zobeck",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Avocet Quael-tai",
    "Player Name": "Mike T",
    "Discord": "Atanamar (Mike T)#8540",
    "Race": "Human",
    "Class": "Beguiler Wizard",
    "Level": 4,
    "Session Points": 29,
    "Status (See Link)": "",
    "Name of Last Session Played": "Who Runs Castle Ranno, Session 6",
    "Date of Last Session": "7/14/2019",
    "Last City Visited": "Ranno (near Triolo)",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "John Henry, Duke of Holliday",
    "Player Name": "Clayton Thomson",
    "Discord": "claytonthomson#8031",
    "Race": "Elfmarked",
    "Class": "Bard (College of Entropy)",
    "Level": 6,
    "Session Points": 51,
    "Status (See Link)": "",
    "Name of Last Session Played": "DMed Gall of the Spider Crone, Session 2",
    "Date of Last Session": "1/23/2019",
    "Last City Visited": "Margreve Forest",
    "System": "D&D5E",
    "Notes": ""
  },
  {
    "Character Name": "Bishop Heahmund Sherborne",
    "Player Name": "Clayton Thomson",
    "Discord": "claytonthomson#8031",
    "Race": "Aasimar",
    "Class": "Paladin (Oath of Conquest)",
    "Level": 5,
    "Session Points": 45,
    "Status (See Link)": "",
    "Name of Last Session Played": "DMed Hell Comes ‘A Glittering, Session 2",
    "Date of Last Session": "2/13/2018",
    "Last City Visited": "Zobeck",
    "System": "D&D5E",
    "Notes": ""
  },
  {
    "Character Name": "Chanzaa kaSenzangakhona",
    "Player Name": "Clayton Thomson",
    "Discord": "claytonthomson#8031",
    "Race": "Werelion",
    "Class": "War Cleric",
    "Level": 5,
    "Session Points": "",
    "Status (See Link)": "",
    "Name of Last Session Played": "Gazing Into Gunnungagap",
    "Date of Last Session": "6/17/2019",
    "Last City Visited": "Zobeck",
    "System": "D&D5E",
    "Notes": ""
  },
  {
    "Character Name": "Oboh Redrum",
    "Player Name": "Clayton Thomson",
    "Discord": "claytonthomson#8031",
    "Race": "Sea Elf",
    "Class": "Fighter/War Mage",
    "Level": 2,
    "Session Points": 4,
    "Status (See Link)": "",
    "Name of Last Session Played": "Ghosts of Saltmarsh",
    "Date of Last Session": "6/1/2019",
    "Last City Visited": "Saltmarsh",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Fargrim Ungart II",
    "Player Name": "Clayton Thomson",
    "Discord": "claytonthomson#8031",
    "Race": "Canton Dwarf (Templeforge)",
    "Class": "Gunslinger",
    "Level": 3,
    "Session Points": 16,
    "Status (See Link)": 1,
    "Name of Last Session Played": "The Sound of Eight Hooves",
    "Date of Last Session": "4/13/2019",
    "Last City Visited": "Thunder Mountain",
    "System": "D&D5E",
    "Notes": ""
  },
  {
    "Character Name": "Judge Roy Maledon",
    "Player Name": "Clayton Thomson",
    "Discord": "claytonthomson#8031",
    "Race": "Dhampir",
    "Class": "Justice Cleric",
    "Level": 5,
    "Session Points": 36,
    "Status (See Link)": "",
    "Name of Last Session Played": "Under the Devil's Thumb",
    "Date of Last Session": "12/2018",
    "Last City Visited": "??",
    "System": "D&D5E",
    "Notes": ""
  },
  {
    "Character Name": "Eternity",
    "Player Name": "Josh R.",
    "Discord": "Cosmosis#0910",
    "Race": "Gearforged",
    "Class": "Paladin",
    "Level": 5,
    "Session Points": 42,
    "Status (See Link)": 7,
    "Name of Last Session Played": "Gristle for Grisal",
    "Date of Last Session": "12/16/2018",
    "Last City Visited": "Zobeck",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Enizu",
    "Player Name": "Josh R.",
    "Discord": "Cosmosis#0910",
    "Race": "Human",
    "Class": "Blood Mage (Wizard)",
    "Level": 2,
    "Session Points": 4,
    "Status (See Link)": 5,
    "Name of Last Session Played": "Journey to the West",
    "Date of Last Session": "4/11/19",
    "Last City Visited": "Barsella",
    "System": "Pathfinder",
    "Notes": ""
  },
  {
    "Character Name": "Varis Sparkclaw",
    "Player Name": "Josh R.",
    "Discord": "Cosmosis#0910",
    "Race": "Bearfolk",
    "Class": "Cleric",
    "Level": 1,
    "Session Points": 2,
    "Status (See Link)": 6,
    "Name of Last Session Played": "Kobold Getto Blaster",
    "Date of Last Session": "1/5/2019",
    "Last City Visited": "Zobeck",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Aleph",
    "Player Name": "Josh R.",
    "Discord": "Cosmosis#0910",
    "Race": "Human",
    "Class": "Futurist (Witch)",
    "Level": 1,
    "Session Points": 1,
    "Status (See Link)": 4,
    "Name of Last Session Played": "Monkey Business",
    "Date of Last Session": "2/20/2019",
    "Last City Visited": "Capleon",
    "System": "Pathfinder",
    "Notes": ""
  },
  {
    "Character Name": "Sean the Destroyer",
    "Player Name": "Sean B.",
    "Discord": "dadofsean",
    "Race": "Minotaur",
    "Class": "Fighter",
    "Level": 8,
    "Session Points": 78,
    "Status (See Link)": "",
    "Name of Last Session Played": "IRL Courts of the Shadow Fey, Session 9",
    "Date of Last Session": "6/19/2019",
    "Last City Visited": "Shadow Realm",
    "System": "D&D5E",
    "Notes": ""
  },
  {
    "Character Name": "Erasto ~ El Guerro Luchadore",
    "Player Name": "Matt Doughty",
    "Discord": "DaggerFortySix#7670",
    "Race": "Variant Human",
    "Class": "Fighter (Battlemaster)",
    "Level": 9,
    "Session Points": 87,
    "Status (See Link)": "",
    "Name of Last Session Played": "IRL Courts of the Shadow Fey, Session 11",
    "Date of Last Session": "7/10/2019",
    "Last City Visited": "Shadow Realm",
    "System": "D&D5E",
    "Notes": ""
  },
  {
    "Character Name": "Lorabella",
    "Player Name": "Dee Kay",
    "Discord": "DeeKay#5518",
    "Race": "Human",
    "Class": "Warlock (Hexblade)",
    "Level": 8,
    "Session Points": "??",
    "Status (See Link)": "",
    "Name of Last Session Played": "Andrew B's One-Shots",
    "Date of Last Session": "",
    "Last City Visited": "",
    "System": "",
    "Notes": ""
  },
  {
    "Character Name": "Thom Flick",
    "Player Name": "DeeKay",
    "Discord": "DeeKay#5518",
    "Race": "Elfmarked",
    "Class": "Rogue (Assassin)",
    "Level": 5,
    "Session Points": 40,
    "Status (See Link)": "",
    "Name of Last Session Played": "The Sunken Library of Qezzit Qire",
    "Date of Last Session": "5/4/2019",
    "Last City Visited": "Tolmezo",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Telgar Ironpants",
    "Player Name": "Chris R.",
    "Discord": "Doctordazzle#6985",
    "Race": "Canton Dwarf",
    "Class": "Life Domain Cleric",
    "Level": 2,
    "Session Points": 8,
    "Status (See Link)": 10,
    "Name of Last Session Played": "In the Name of Khors",
    "Date of Last Session": "5/31/2019",
    "Last City Visited": "Zobeck",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Crash",
    "Player Name": "",
    "Discord": "Gambler#1724",
    "Race": "Aasimar",
    "Class": "Barbarian",
    "Level": 2,
    "Session Points": 4,
    "Status (See Link)": "",
    "Name of Last Session Played": "Welcome to the Garden",
    "Date of Last Session": "5/3/2019",
    "Last City Visited": "River Court of Arbonesse",
    "System": "D&F 5E",
    "Notes": ""
  },
  {
    "Character Name": "Gamble",
    "Player Name": "Dan Bartels",
    "Discord": "Gambler1304#1724",
    "Race": "Trollkin",
    "Class": "Barbarian",
    "Level": 7,
    "Session Points": 60,
    "Status (See Link)": "",
    "Name of Last Session Played": "IRL Courts of the Shadow Fey, Session 11",
    "Date of Last Session": "7/10/2019",
    "Last City Visited": "Shadow Realm",
    "System": "D&D 5e",
    "Notes": ""
  },
  {
    "Character Name": "Kenyon Shark Bait McGee",
    "Player Name": "Dan",
    "Discord": "Gambler1304#1724",
    "Race": "Night Whisper Trollkin",
    "Class": "Path of the Storm Herald Barbarian",
    "Level": 4,
    "Session Points": 29,
    "Status (See Link)": "",
    "Name of Last Session Played": "Who Runs Castle Ranno, Session 6",
    "Date of Last Session": "7/14/2019",
    "Last City Visited": "Ranno (near Triolo)",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Zadar Tramplehoof",
    "Player Name": "Chris Taylor",
    "Discord": "GunbunnyFuFu#9763",
    "Race": "Centaur",
    "Class": "Fighter",
    "Level": 2,
    "Session Points": 4,
    "Status (See Link)": 3,
    "Name of Last Session Played": "Gears for the Clankers",
    "Date of Last Session": "07/18/2018",
    "Last City Visited": "White Mountain Marches",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Stefano Ricci",
    "Player Name": "Chris Taylor",
    "Discord": "GunbunnyFuFu#9763",
    "Race": "Human (Standard)",
    "Class": "Paladin",
    "Level": 2,
    "Session Points": 9,
    "Status (See Link)": 7,
    "Name of Last Session Played": "Lost Hall of the Everforge",
    "Date of Last Session": "5/18/2019",
    "Last City Visited": "Barenna",
    "System": "D&D5E",
    "Notes": ""
  },
  {
    "Character Name": "Korwyn the Reaver",
    "Player Name": "Chris Taylor",
    "Discord": "GunbunnyFuFu#9763",
    "Race": "Minotaur",
    "Class": "Fighter (Battlemaster)",
    "Level": 5,
    "Session Points": 40,
    "Status (See Link)": 5,
    "Name of Last Session Played": "Neither By Sail, Nor By Oar",
    "Date of Last Session": "9/27/2018",
    "Last City Visited": "Laksor (Nuria Natal)",
    "System": "D&D5E",
    "Notes": ""
  },
  {
    "Character Name": "Rusty Gearsprings",
    "Player Name": "Chris Taylor",
    "Discord": "GunbunnyFuFu#9763",
    "Race": "Human (Gearforged)",
    "Class": "Fighter",
    "Level": 2,
    "Session Points": 8,
    "Status (See Link)": "3 (4 in  Thunder Mountain)",
    "Name of Last Session Played": "The Sound of Eight Hooves",
    "Date of Last Session": "4/13/2019",
    "Last City Visited": "Thunder Mountain",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Pearl Sarya",
    "Player Name": "Owen W",
    "Discord": "HCCasual#0079",
    "Race": "Elfmarked",
    "Class": "Rogue / Fighter",
    "Level": "2/1",
    "Session Points": 14,
    "Status (See Link)": "",
    "Name of Last Session Played": "The Old Marblehead Lighthouse [Extended Cut]",
    "Date of Last Session": "7/13/2019",
    "Last City Visited": "Bjeornheim",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Vispin",
    "Player Name": "Jeremy",
    "Discord": "Highlord#0763",
    "Race": "Bearfolk",
    "Class": "Monk",
    "Level": 3,
    "Session Points": 15,
    "Status (See Link)": 5,
    "Name of Last Session Played": "The Maiden",
    "Date of Last Session": "6/29/2019",
    "Last City Visited": "Savoyne",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Alma Cropley",
    "Player Name": "Brian Hubbard",
    "Discord": "hubs72#2098",
    "Race": "Hafling",
    "Class": "Fighter Champion",
    "Level": 9,
    "Session Points": 90,
    "Status (See Link)": "",
    "Name of Last Session Played": "IRL Courts of the Shadow Fey, Session 8",
    "Date of Last Session": "6/12/2019",
    "Last City Visited": "Zobeck",
    "System": "D&D 5e",
    "Notes": ""
  },
  {
    "Character Name": "Emir Bassura",
    "Player Name": "Kipp Cozad",
    "Discord": "Jadedsage(Emir Bassura)#8940",
    "Race": "Tabaxi (Southlands Catfolk)",
    "Class": "Duelest Rogue",
    "Level": 5,
    "Session Points": 39,
    "Status (See Link)": "",
    "Name of Last Session Played": "IRL Courts of the Shadow Fey, Session 9",
    "Date of Last Session": "6/19/2019",
    "Last City Visited": "Shadow Realm",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Whurbin Dunkil",
    "Player Name": "Jason R",
    "Discord": "Jason R#6263",
    "Race": "Mountain Dwarf",
    "Class": "Ring Warden Wizard",
    "Level": 3,
    "Session Points": 20,
    "Status (See Link)": 7,
    "Name of Last Session Played": "Down in a Hole",
    "Date of Last Session": "5/10/2019",
    "Last City Visited": "Vespras",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Magdalena",
    "Player Name": "Jason R",
    "Discord": "Jason R#6263",
    "Race": "Dhampir",
    "Class": "Duelist Rogue",
    "Level": 3,
    "Session Points": 17,
    "Status (See Link)": "",
    "Name of Last Session Played": "Lost Hall of the Everforge",
    "Date of Last Session": "5/18/2019",
    "Last City Visited": "Barenna",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Rafparin",
    "Player Name": "Jason R",
    "Discord": "Jason R#6263",
    "Race": "elfmarked",
    "Class": "Warlock (Old wood)",
    "Level": 2,
    "Session Points": 3,
    "Status (See Link)": "",
    "Name of Last Session Played": "The Maiden",
    "Date of Last Session": "6/29/2019",
    "Last City Visited": "Savoyne",
    "System": "D&D5E",
    "Notes": ""
  },
  {
    "Character Name": "Zerbeik",
    "Player Name": "John Wyzkiewicz",
    "Discord": "JohnTheBrewer#7279",
    "Race": "Gearforged",
    "Class": "Rogue (Duelist)",
    "Level": 2,
    "Session Points": 4,
    "Status (See Link)": "",
    "Name of Last Session Played": "Bastion of Rime and Salt",
    "Date of Last Session": "1/9/19",
    "Last City Visited": "Zobeck",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Eris Nightflyer",
    "Player Name": "John Wyzkiewicz",
    "Discord": "JohnTheBrewer#7279",
    "Race": "Damphir",
    "Class": "Wizard (Necrophage)",
    "Level": 9,
    "Session Points": 93,
    "Status (See Link)": "",
    "Name of Last Session Played": "IRL Courts of the Shadow Fey, Session 9",
    "Date of Last Session": "6/19/2019",
    "Last City Visited": "Shadow Realm",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Inga Opelbok",
    "Player Name": "Justin C",
    "Discord": "JustinC#6457",
    "Race": "Windrunner Elf",
    "Class": "Monk (Kensei)",
    "Level": 6,
    "Session Points": 51,
    "Status (See Link)": "",
    "Name of Last Session Played": "Run Like Hell",
    "Date of Last Session": "6/7/2019",
    "Last City Visited": "Stalimisto",
    "System": "D&D5E",
    "Notes": ""
  },
  {
    "Character Name": "Azini Da'Ranno",
    "Player Name": "Mitch P",
    "Discord": "Lazzamore#6937",
    "Race": "Human (variant)",
    "Class": "Fighter",
    "Level": 2,
    "Session Points": 7,
    "Status (See Link)": "",
    "Name of Last Session Played": "Anura Craugastoridae",
    "Date of Last Session": "4/15/2019",
    "Last City Visited": "Barsella",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Mingair",
    "Player Name": "Mitch P",
    "Discord": "Lazzamore#6937",
    "Race": "Elf (Arbonesse)",
    "Class": "Wizard (Enchanting)",
    "Level": 5,
    "Session Points": 36,
    "Status (See Link)": "",
    "Name of Last Session Played": "Golem in the Gears",
    "Date of Last Session": "3/20/19",
    "Last City Visited": "Barsella",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Wen-Mela",
    "Player Name": "Mitch P",
    "Discord": "Lazzamore#6937",
    "Race": "Elf (Arbonesse)",
    "Class": "Ranger",
    "Level": 2,
    "Session Points": 4,
    "Status (See Link)": "",
    "Name of Last Session Played": "In the Name of Khors",
    "Date of Last Session": "3/22/2019",
    "Last City Visited": "Zobeck",
    "System": "D&D5E",
    "Notes": ""
  },
  {
    "Character Name": "Id",
    "Player Name": "Mitch P",
    "Discord": "Lazzamore#6937",
    "Race": "human",
    "Class": "Life Domain Cleric",
    "Level": 5,
    "Session Points": 30,
    "Status (See Link)": "",
    "Name of Last Session Played": "Sanctuary of Belches",
    "Date of Last Session": "5/16/2019",
    "Last City Visited": "Olsha",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Cimmeriel the Younger",
    "Player Name": "Mitch P",
    "Discord": "Lazzamore#6957",
    "Race": "Alseid",
    "Class": "Sword Dancer Fighter",
    "Level": 3,
    "Session Points": 20,
    "Status (See Link)": "",
    "Name of Last Session Played": "Ooze Who?",
    "Date of Last Session": "6/26/2019",
    "Last City Visited": "Maillon",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Runa",
    "Player Name": "",
    "Discord": "Luka#5563",
    "Race": "Human",
    "Class": "Hexblade Warlock 1/ College of the Blade Bard 4",
    "Level": 5,
    "Session Points": 36,
    "Status (See Link)": "",
    "Name of Last Session Played": "Sanctuary of Belches",
    "Date of Last Session": "5/16/2019",
    "Last City Visited": "Olsha",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Mare",
    "Player Name": "Luka",
    "Discord": "Luka#5563",
    "Race": "Human Elf-marked",
    "Class": "Wild Magic Sorcerer",
    "Level": 4,
    "Session Points": 24,
    "Status (See Link)": "",
    "Name of Last Session Played": "The Old Marblehead Lighthouse [Extended Cut]",
    "Date of Last Session": "7/13/2019",
    "Last City Visited": "Bjeornheim",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Ragna",
    "Player Name": "",
    "Discord": "Luka#5563",
    "Race": "Tiefling",
    "Class": "Nameless Warlock Playtest",
    "Level": 4,
    "Session Points": 34,
    "Status (See Link)": "",
    "Name of Last Session Played": "Who Runs Castle Ranno, Session 6",
    "Date of Last Session": "7/14/2019",
    "Last City Visited": "Ranno (near Triolo)",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Akluthov Kothach",
    "Player Name": "Malkuth",
    "Discord": "malkuth#3954",
    "Race": "Bearfolk (Grizzlehide)",
    "Class": "Barbarian",
    "Level": 3,
    "Session Points": 16,
    "Status (See Link)": "",
    "Name of Last Session Played": "A Starry Breach",
    "Date of Last Session": "6/25/2019",
    "Last City Visited": "Bjeornheim",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Vuöru Huinen Ukkosta",
    "Player Name": "Malkuth",
    "Discord": "malkuth#3954",
    "Race": "Trollkin",
    "Class": "Fighter (Dragoon)",
    "Level": 5,
    "Session Points": 39,
    "Status (See Link)": "",
    "Name of Last Session Played": "Run Like Hell",
    "Date of Last Session": "6/7/2019",
    "Last City Visited": "Stalimisto",
    "System": "D&D5E",
    "Notes": ""
  },
  {
    "Character Name": "Malkuth*",
    "Player Name": "Malkuth",
    "Discord": "malkuth#3954",
    "Race": "Human*",
    "Class": "Warlock*",
    "Level": 2,
    "Session Points": 9,
    "Status (See Link)": "",
    "Name of Last Session Played": "The Old Marblehead Lighthouse [Extended Cut]",
    "Date of Last Session": "7/13/2019",
    "Last City Visited": "Bjeornheim",
    "System": "D&D5E",
    "Notes": "* DM should consult with player for background details"
  },
  {
    "Character Name": "Seigur Dvelurmethtrjowm",
    "Player Name": "Malkuth",
    "Discord": "Malkuth#3954",
    "Race": "Gearforged",
    "Class": "Fey Magic Sorcerer",
    "Level": 4,
    "Session Points": 29,
    "Status (See Link)": "",
    "Name of Last Session Played": "Who Runs Castle Ranno, Session 6",
    "Date of Last Session": "7/14/2019",
    "Last City Visited": "Ranno (near Triolo)",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Razziks",
    "Player Name": "Mark G",
    "Discord": "Mark G#4369",
    "Race": "Aasimar",
    "Class": "Celestial Warlock",
    "Level": 3,
    "Session Points": 14,
    "Status (See Link)": "",
    "Name of Last Session Played": "The Old Marblehead Lighthouse [Extended Cut]",
    "Date of Last Session": "7/13/2019",
    "Last City Visited": "Bjeornheim",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Berask Rostager",
    "Player Name": "Mark G.",
    "Discord": "Mark#4369",
    "Race": "Human(standard)",
    "Class": "Ranger(Horizon Walker) / Rogue",
    "Level": "5/1",
    "Session Points": 48,
    "Status (See Link)": 15,
    "Name of Last Session Played": "Courts of the Shadow Fey, Session 2 - Online",
    "Date of Last Session": "4/13/2019",
    "Last City Visited": "Zobeck",
    "System": "D&D5E",
    "Notes": ""
  },
  {
    "Character Name": "Brynjar the Blessed",
    "Player Name": "Robert Jazo",
    "Discord": "Medraut#7701",
    "Race": "Variant Human",
    "Class": "Paladin (Ancients)",
    "Level": 8,
    "Session Points": 82,
    "Status (See Link)": "17 (8 in Trombei)",
    "Name of Last Session Played": "Courts of the Shadow Fey, Session 3 - Online",
    "Date of Last Session": "5/11/2018",
    "Last City Visited": "Zobeck",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Dair Dhenen",
    "Player Name": "Robert Jazo",
    "Discord": "Medraut#7701",
    "Race": "Elfmarked",
    "Class": "Cleric (Trickery) / Rogue",
    "Level": "3/1",
    "Session Points": 24,
    "Status (See Link)": 8,
    "Name of Last Session Played": "In the Name of Khors",
    "Date of Last Session": "3/22/2019",
    "Last City Visited": "Zobeck",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Medraut Larentil",
    "Player Name": "Robert Jazo",
    "Discord": "Medraut#7701",
    "Race": "River Elf",
    "Class": "Wizard (Diviner)",
    "Level": 6,
    "Session Points": 56,
    "Status (See Link)": "7 (8 in Per-Bastet)",
    "Name of Last Session Played": "The Sunken Library of Qezzit Qire",
    "Date of Last Session": "5/4/2019",
    "Last City Visited": "Tolmezo",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Yenteel",
    "Player Name": "Sean",
    "Discord": "ObnoxSean#9569",
    "Race": "Orc",
    "Class": "Paladin",
    "Level": 2,
    "Session Points": 3,
    "Status (See Link)": "",
    "Name of Last Session Played": "Ooze Who?",
    "Date of Last Session": "6/26/2019",
    "Last City Visited": "Maillon",
    "System": "D&D5E",
    "Notes": ""
  },
  {
    "Character Name": "Tonni , the Tenebrous",
    "Player Name": "Peter G",
    "Discord": "Peter G.#3048",
    "Race": "Minotaur",
    "Class": "Cleric",
    "Level": 5,
    "Session Points": 39,
    "Status (See Link)": "",
    "Name of Last Session Played": "Run Like Hell",
    "Date of Last Session": "6/7/2019",
    "Last City Visited": "Stalimisto",
    "System": "D&D5E",
    "Notes": ""
  },
  {
    "Character Name": "Dryszys",
    "Player Name": "Quintain",
    "Discord": "Quintain#8121",
    "Race": "Ravenfolk",
    "Class": "Rogue Assassin",
    "Level": 4,
    "Session Points": 32,
    "Status (See Link)": "",
    "Name of Last Session Played": "Sanctuary of Belches",
    "Date of Last Session": "5/16/19",
    "Last City Visited": "Olsha",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Kuligash",
    "Player Name": "Quintain",
    "Discord": "Quintain#8121",
    "Race": "Human Elf-marked",
    "Class": "Hexblade Warlock",
    "Level": 5,
    "Session Points": 40,
    "Status (See Link)": "",
    "Name of Last Session Played": "The Old Marblehead Lighthouse [Extended Cut]",
    "Date of Last Session": "7/13/2019",
    "Last City Visited": "Bjeornheim",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Rout",
    "Player Name": "B",
    "Discord": "radfemmefatale#4706",
    "Race": "Tiefling",
    "Class": "Paladin",
    "Level": 3,
    "Session Points": 13,
    "Status (See Link)": 6,
    "Name of Last Session Played": "Above Blue Blocks",
    "Date of Last Session": "5/25/2019",
    "Last City Visited": "Tintager",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Uriel",
    "Player Name": "Roger Garza",
    "Discord": "rogermgarza#7403",
    "Race": "Aasimar (Protector)",
    "Class": "Divine Soul Sorcerer",
    "Level": 2,
    "Session Points": 4,
    "Status (See Link)": "",
    "Name of Last Session Played": "A Starry Breach",
    "Date of Last Session": "6/25/2019",
    "Last City Visited": "Bjeornheim",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Syduk Masad",
    "Player Name": "Roger Garza",
    "Discord": "rogermgarza#7403",
    "Race": "Jinnborn",
    "Class": "Rogue Scout",
    "Level": 8,
    "Session Points": 74,
    "Status (See Link)": 15,
    "Name of Last Session Played": "Courts of the Shadow Fey, Session 3 - Online",
    "Date of Last Session": "5/11/2018",
    "Last City Visited": "Zobeck",
    "System": "D&D 5e",
    "Notes": ""
  },
  {
    "Character Name": "Elohim Fenmarel",
    "Player Name": "Roger Garza",
    "Discord": "rogermgarza#7403",
    "Race": "Elfmarked",
    "Class": "Blood Hunter/Sorcerer",
    "Level": "1/1",
    "Session Points": 9,
    "Status (See Link)": "",
    "Name of Last Session Played": "Lost Hall of the Everforge",
    "Date of Last Session": "5/18/2019",
    "Last City Visited": "Barenna",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Selim",
    "Player Name": "Roger Garza",
    "Discord": "rogermgarza#7403",
    "Race": "Dragonborn (Edjet)",
    "Class": "Fighter Edjet",
    "Level": 4,
    "Session Points": 22,
    "Status (See Link)": "",
    "Name of Last Session Played": "Sanctuary of Belches",
    "Date of Last Session": "5/16/19",
    "Last City Visited": "Olsha",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Iteru Wasat",
    "Player Name": "roger Garza",
    "Discord": "rogermgarza#7403",
    "Race": "Ravenfolk",
    "Class": "Rogue/Pantheist Priest",
    "Level": 4,
    "Session Points": 27,
    "Status (See Link)": "",
    "Name of Last Session Played": "The Maiden",
    "Date of Last Session": "6/29/2019",
    "Last City Visited": "savoyne",
    "System": "D&D5E",
    "Notes": ""
  },
  {
    "Character Name": "Stokely Holderhek",
    "Player Name": "Roger Garza",
    "Discord": "rogermgarza#7403",
    "Race": "Shade (dwarf)",
    "Class": "Gunslinger Fighter",
    "Level": 4,
    "Session Points": 29,
    "Status (See Link)": "",
    "Name of Last Session Played": "Who Runs Castle Ranno, Session 6",
    "Date of Last Session": "7/14/2019",
    "Last City Visited": "Ranno (near Triolo)",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Jyckall",
    "Player Name": "Mike Lund",
    "Discord": "RY#7795",
    "Race": "Aasimar",
    "Class": "Cleric",
    "Level": 8,
    "Session Points": 83,
    "Status (See Link)": "",
    "Name of Last Session Played": "IRL Courts of the Shadow Fey, Session 9",
    "Date of Last Session": "6/19/2019",
    "Last City Visited": "Shadow Realm",
    "System": "D&D5E",
    "Notes": ""
  },
  {
    "Character Name": "Ander Rirko",
    "Player Name": "RyanJ",
    "Discord": "RyanJ#8719",
    "Race": "Variant Human",
    "Class": "Rogue",
    "Level": 2,
    "Session Points": 8,
    "Status (See Link)": 7,
    "Name of Last Session Played": "Above Blue Blocks",
    "Date of Last Session": "5/25/2019",
    "Last City Visited": "Tintager",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Merry Christmas /Frosty",
    "Player Name": "Lisa Jasinski",
    "Discord": "Shieldmaiden Gunhild",
    "Race": "Winterfolk halfling/snow cat",
    "Class": "Sorcerer (silver dragon bloodline)",
    "Level": "10/6",
    "Session Points": 101,
    "Status (See Link)": "",
    "Name of Last Session Played": "IRL Courts of the Shadow Fey, Session 11",
    "Date of Last Session": "7/10/2019",
    "Last City Visited": "Shadow Realm",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Heimdall",
    "Player Name": "Samantha Jasinski",
    "Discord": "Shieldmaiden Gunhild",
    "Race": "Civilized Gnoll",
    "Class": "Fighter (Champion)",
    "Level": 10,
    "Session Points": 109,
    "Status (See Link)": "",
    "Name of Last Session Played": "IRL Courts of the Shadow Fey, Session 11",
    "Date of Last Session": "7/10/2019",
    "Last City Visited": "Shadow Realm",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Quinton Steel",
    "Player Name": "Trevor L.",
    "Discord": "Shiki#0285",
    "Race": "Human (Elfmarked)",
    "Class": "Warlock (Hexblade) / Fighter",
    "Level": 6,
    "Session Points": 58,
    "Status (See Link)": 17,
    "Name of Last Session Played": "Courts of the Shadow Fey, Session 3 - Online",
    "Date of Last Session": "5/11/2018",
    "Last City Visited": "Zobeck",
    "System": "D&D5E",
    "Notes": ""
  },
  {
    "Character Name": "Scribbler",
    "Player Name": "Trevor L.",
    "Discord": "Shiki#0285",
    "Race": "Ratfolk",
    "Class": "Wizard",
    "Level": 3,
    "Session Points": 23,
    "Status (See Link)": "",
    "Name of Last Session Played": "Ooze Who?",
    "Date of Last Session": "6/26/2019",
    "Last City Visited": "Maillon",
    "System": "D&D5E",
    "Notes": ""
  },
  {
    "Character Name": "Elham",
    "Player Name": "Trevor L.",
    "Discord": "Shiki#0285",
    "Race": "Tabaxi (Southlands Catfolk)",
    "Class": "Monk (Way of the Kensei) / Ranger",
    "Level": 5,
    "Session Points": 48,
    "Status (See Link)": 4,
    "Name of Last Session Played": "Run Like Hell",
    "Date of Last Session": "6/7/2019",
    "Last City Visited": "Stalimisto",
    "System": "D&D5E",
    "Notes": ""
  },
  {
    "Character Name": "Mithrielye Suron",
    "Player Name": "Noland Higgins",
    "Discord": "TBD",
    "Race": "River Elf",
    "Class": "Fighter Battle Master",
    "Level": 6,
    "Session Points": 48,
    "Status (See Link)": "",
    "Name of Last Session Played": "IRL Courts of the Shadow Fey, Session 11",
    "Date of Last Session": "7/10/2019",
    "Last City Visited": "Shadow Realm",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Sheev of Utensylvania",
    "Player Name": "Mark I.",
    "Discord": "tempymark#6682",
    "Race": "Elf",
    "Class": "Warlock Hexblade",
    "Level": 6,
    "Session Points": 58,
    "Status (See Link)": 17,
    "Name of Last Session Played": "Courts of the Shadow Fey, Session 3 - Online",
    "Date of Last Session": "5/11/2018",
    "Last City Visited": "Zobeck",
    "System": "D&D 5e",
    "Notes": ""
  },
  {
    "Character Name": "Grand Iwae",
    "Player Name": "Griffin H",
    "Discord": "Yenrah#5149",
    "Race": "Derro",
    "Class": "College of the Muse Bard",
    "Level": 4,
    "Session Points": 28,
    "Status (See Link)": "",
    "Name of Last Session Played": "A Starry Breach",
    "Date of Last Session": "6/25/2019",
    "Last City Visited": "Bjeornheim",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Momotaros",
    "Player Name": "Griffin H",
    "Discord": "Yenrah#5149",
    "Race": "Alseid",
    "Class": "Ranger Spear of the Wyld",
    "Level": 3,
    "Session Points": 13,
    "Status (See Link)": "",
    "Name of Last Session Played": "Above Blue Blocks",
    "Date of Last Session": "5/25/2019",
    "Last City Visited": "Tintager",
    "System": "",
    "Notes": ""
  },
  {
    "Character Name": "Kiva Trollbreaker",
    "Player Name": "Griffin H",
    "Discord": "Yenrah#5149",
    "Race": "Winterfolk Halfling",
    "Class": "Fighter (Griffon Knight)",
    "Level": 4,
    "Session Points": 35,
    "Status (See Link)": "",
    "Name of Last Session Played": "An Immovable Feast",
    "Date of Last Session": "6/12/19",
    "Last City Visited": "Bad Solitz",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Zabee Woetooth (Hornet)",
    "Player Name": "Griffin H",
    "Discord": "Yenrah#5149",
    "Race": "Civilized Gnoll",
    "Class": "Sorcerer (Divine Soul)",
    "Level": 3,
    "Session Points": 20,
    "Status (See Link)": "",
    "Name of Last Session Played": "For Science",
    "Date of Last Session": "4/26/19",
    "Last City Visited": "Thunder Mountain",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Decade Woz",
    "Player Name": "Griffin H",
    "Discord": "Yenrah#5149",
    "Race": "Sea Elf",
    "Class": "Wizard (Angelic Scribe)",
    "Level": 6,
    "Session Points": 55,
    "Status (See Link)": "",
    "Name of Last Session Played": "Run Like Hell",
    "Date of Last Session": "6/7/2019",
    "Last City Visited": "Stalimisto",
    "System": "D&D5E",
    "Notes": ""
  },
  {
    "Character Name": "Krim Steinbelt",
    "Player Name": "Griffin H",
    "Discord": "Yenrah#5149",
    "Race": "Minotaur",
    "Class": "Great Machine Warlock",
    "Level": 3,
    "Session Points": 17,
    "Status (See Link)": "",
    "Name of Last Session Played": "The Impregnable Fortress of Dib",
    "Date of Last Session": "5/11/2019",
    "Last City Visited": "Whitesparrow, Northlands",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Marko Claychain",
    "Player Name": "Griffin H",
    "Discord": "Yenrah#5149",
    "Race": "Dueragar",
    "Class": "Paladin (Conquest)",
    "Level": 6,
    "Session Points": 48,
    "Status (See Link)": "",
    "Name of Last Session Played": "The Lady Vanishes",
    "Date of Last Session": "1/19/19",
    "Last City Visited": "Free City of Salzbach",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Ixa Rook",
    "Player Name": "Griffin H",
    "Discord": "Yenrah#5149",
    "Race": "Nkosi",
    "Class": "Divine Herald Rogue",
    "Level": 4,
    "Session Points": 29,
    "Status (See Link)": "",
    "Name of Last Session Played": "Who Runs Castle Ranno, Session 6",
    "Date of Last Session": "7/14/2019",
    "Last City Visited": "Ranno (near Triolo)",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Raven",
    "Player Name": "Nick Wolnik",
    "Discord": "Zane_Blackfire723#5704",
    "Race": "Elfmarked",
    "Class": "Nameless Warlock Playtest",
    "Level": 10,
    "Session Points": 105,
    "Status (See Link)": "",
    "Name of Last Session Played": "IRL Courts of the Shadow Fey, Session 11",
    "Date of Last Session": "7/10/2019",
    "Last City Visited": "Shadow Realm",
    "System": "D&D 5e",
    "Notes": ""
  },
  {
    "Character Name": "Briar",
    "Player Name": "Noa R.",
    "Discord": "ZippyOW#7496",
    "Race": "Tiefling",
    "Class": "Druid (Circle of the Shepherd)",
    "Level": 3,
    "Session Points": 16,
    "Status (See Link)": "",
    "Name of Last Session Played": "For Science",
    "Date of Last Session": "4/26/2019",
    "Last City Visited": "Thunder Mountain",
    "System": "D&D5E",
    "Notes": ""
  },
  {
    "Character Name": "Valentine",
    "Player Name": "Kalen Carrelli",
    "Discord": "",
    "Race": "Human",
    "Class": "Rogue",
    "Level": 5,
    "Session Points": 39,
    "Status (See Link)": "",
    "Name of Last Session Played": "IRL Courts of the Shadow Fey, Session 4",
    "Date of Last Session": "5/22/2019",
    "Last City Visited": "Zobeck",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Myrna Octavian",
    "Player Name": "Marco Garcia",
    "Discord": "",
    "Race": "Canton Dwarf",
    "Class": "Fighter Champion",
    "Level": 5,
    "Session Points": 42,
    "Status (See Link)": "",
    "Name of Last Session Played": "IRL Courts of the Shadow Fey, Session 5",
    "Date of Last Session": "5/29/2019",
    "Last City Visited": "Zobeck",
    "System": "D&D 5E",
    "Notes": ""
  },
  {
    "Character Name": "Gork",
    "Player Name": "Jacob Lund",
    "Discord": "",
    "Race": "Half-orc",
    "Class": "Fighter",
    "Level": 6,
    "Session Points": 65,
    "Status (See Link)": "",
    "Name of Last Session Played": "IRL Courts of the Shadow Fey, Session 9",
    "Date of Last Session": "6/19/2019",
    "Last City Visited": "Shadow Realm",
    "System": "D&D5E",
    "Notes": ""
  }
]
function processAllData(allData) {
  return Promise.mapSeries(allData, data => {
    return processData(data)
  })
}

async function processData(data) {
  try{
    if(data["Discord"]) {
      let session = await processSession(data)
      let player = await processPlayer(data)
      let character = await processCharacter(data, player, session)
      return character
    } else {
      console.log('data has no discord name, skipping')
      return Promise.resolve()
    }
  } catch(e){
    console.log(e)
    return Promise.resolve()
  }
}

async function processSession(data){
  let sessionName = data["Name of Last Session Played"]
  let date = data["Date of Last Session"]
  let sessionToProcess = await Session.findOne(
    {
      sessionName: data["Name of Last Session Played"],
      date: data["Date of Last Session"]
    })
  if(sessionToProcess) {
    console.log('session already exists')
    return sessionToProcess
  } else {
    let newSession = new Session({
      sessionName: data["Name of Last Session Played"],
      date: data["Date of Last Session"],
      city: data["Last City Visited"],
      system: data["System"]
    })
    await newSession.save()
    console.log('saving session:', newSession.name)
    return newSession
  }
}

async function processPlayer(data) {
  let foundPlayer = await Player.findOne({discordUserName: data["Discord"]})
  if(foundPlayer) {
    console.log('player already exists')
    return foundPlayer
  } else {
    let newPlayer = new Player({
      playerName: data["Player Name"],
      discordUserName: data["Discord"],
    })
    await newPlayer.save()
    console.log('creating player')
    return newPlayer
  }
}

async function processCharacter(data, player, session) {
  let newCharacter = new Character({
    player: player._id,
    lastSessionPlayed: session._id,
    characterName: data["Character Name"],
    level: data["Level"],
    class: data["Class"],
    race: data["Race"],
    sessionPoints: data["Session Points"],
    status: 0
  })
  await newCharacter.save()
}

processAllData(allData)
.then(() => {
  console.log('done')
  process.exit()
})
// console.log('Players:', JSON.stringify(players, null, 2))
// console.log('Sessions:', JSON.stringify(sessions, null, 2))
// console.log('Characters:', JSON.stringify(characters, null, 2))



